server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
              # It compares the URL path /api/auth/login with the route predicate:
              # Path=/api/auth/**  : MATCH FOUND â†’ So this request belongs to auth-service route.
              # Gateway Forwards the Request : http://localhost:8081
              # Gateway rewrites internally:  http://localhost:8081/api/auth/login
              # And sends the request to auth-service.

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
          filters:
                - StripPrefix=1

        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**

        - id: cart-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**

        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/orders/**

        - id: sales-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/sales/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
